//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIMonitor
    {
        public int MonitorID { get; set; }
        public string UUID { get; set; }
        public string APIName { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
