//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Role
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int RoleId { get; set; }
        public string RoleDescription { get; set; }
        public string OptionText { get; set; }
        public string OptionValue { get; set; }
        public string OptionType { get; set; }
        public int Ordering { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
