//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_APIAccessKey
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int APIAccessKeyID { get; set; }
        public string TokenCode { get; set; }
        public string AccessKey { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UserId_FK { get; set; }
    }
}
