//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_BillingProposal
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int BillingProposalID { get; set; }
        public int PatientID_FK { get; set; }
        public string ProposalNumber { get; set; }
        public string Title { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<bool> EmailPatient { get; set; }
        public string EmailTo { get; set; }
        public string EmailCC { get; set; }
        public string EmailBCC { get; set; }
        public int CurrencyID_FK { get; set; }
        public decimal TotalCost { get; set; }
        public string Status { get; set; }
        public string GroupNumber { get; set; }
        public short Version { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
        public string ProposalType { get; set; }
    }
}
