//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_EnquiryConfig
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int EnquiryConfigID { get; set; }
        public Nullable<int> SCMID_FK { get; set; }
        public string EmailContent { get; set; }
        public Nullable<int> EscalatingPersonID_FK { get; set; }
        public Nullable<decimal> EscalationPeriod { get; set; }
        public string EscalationEmail { get; set; }
        public string EmailtoCMContent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
