//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_VitalSignTypeThreshold
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int VitalSignTypeID_FK { get; set; }
        public Nullable<decimal> ews_min_1 { get; set; }
        public Nullable<decimal> ews_max_1 { get; set; }
        public Nullable<decimal> ews_min_2 { get; set; }
        public Nullable<decimal> ews_max_2 { get; set; }
        public Nullable<decimal> ews_min_3 { get; set; }
        public Nullable<decimal> ews_max_3 { get; set; }
        public Nullable<decimal> ews_min_4 { get; set; }
        public Nullable<decimal> ews_max_4 { get; set; }
        public Nullable<decimal> ews_min_5 { get; set; }
        public Nullable<decimal> ews_max_5 { get; set; }
        public Nullable<decimal> ews_min_6 { get; set; }
        public Nullable<decimal> ews_max_6 { get; set; }
        public Nullable<decimal> ews_min_7 { get; set; }
        public Nullable<decimal> ews_max_7 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
    }
}
