//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_PatientReferral
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int PatientReferralID { get; set; }
        public Nullable<int> PrimaryClinicianID_FK { get; set; }
        public Nullable<int> SecondaryClinicianID_FK { get; set; }
        public Nullable<bool> PatientAwareDiagnose { get; set; }
        public Nullable<bool> FamilyAwareDiagnose { get; set; }
        public Nullable<bool> PatientAwarePrognosis { get; set; }
        public Nullable<bool> FamilyAwarePrognosis { get; set; }
        public string PatientAwareDiagnoseReason { get; set; }
        public string FamilyAwareDiagnoseReason { get; set; }
        public string PatientAwarePrognosisReason { get; set; }
        public string FamilyAwarePrognosisReason { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public Nullable<int> PrimaryNurseID_FK { get; set; }
        public Nullable<int> SecondaryNurseID_FK { get; set; }
    }
}
