//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_BillingPackage
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public Nullable<int> ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Type { get; set; }
        public Nullable<int> Session { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> Validity { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public int BillingServiceID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
    }
}
