//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_CarePlanSubGoal
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int CarePlanSubGoalID { get; set; }
        public int CarePlanSubID_FK { get; set; }
        public Nullable<int> ScoreTypeID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<decimal> Score1 { get; set; }
        public Nullable<decimal> Score2 { get; set; }
        public string CarePlanSubGoalName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public Nullable<int> DiseaseID_FK { get; set; }
    }
}
