//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_SyncWoundVisitLog
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int SyncLogId { get; set; }
        public int SyncBatchTs { get; set; }
        public int OffWoundVisitID { get; set; }
        public int ServerWoundID { get; set; }
        public int ServerWoundVisitID { get; set; }
        public bool SyncResult { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
    }
}
