//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_InitialCareAssessmentAttachment
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int InitialCareAssessmentAttachmentID { get; set; }
        public int InitialCareAssessmentID_FK { get; set; }
        public string Filename { get; set; }
        public string Physical { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsReferralAssessment { get; set; }
        public bool IsDischargeAssessment { get; set; }
        public bool IsDeleted { get; set; }
    }
}
