//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_PatientFamilyHistory
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int PatientFamilyHistoryID { get; set; }
        public Nullable<int> PatientID_FK { get; set; }
        public Nullable<int> InitialCareAssessmentID_FK { get; set; }
        public int DiseaseID_FK { get; set; }
        public Nullable<int> DiseaseSubInfoID_FK { get; set; }
        public Nullable<int> YearDiagnose { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
        public string Relationship { get; set; }
    }
}
