//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_ProblemListGoal
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int ProblemListGoalID { get; set; }
        public int ProblemListID_FK { get; set; }
        public string Goal { get; set; }
        public Nullable<int> Action { get; set; }
        public Nullable<int> ScoreTypeID { get; set; }
        public Nullable<int> OperatorID { get; set; }
    }
}
