//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_PatientMedicationConsume
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int PatientMedicationConsumeID { get; set; }
        public int PatientMedicationID_FK { get; set; }
        public Nullable<int> MedicationID_FK { get; set; }
        public Nullable<int> RouteID_FK { get; set; }
        public Nullable<int> DosageID_FK { get; set; }
        public Nullable<int> FrequencyID_FK { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Indication { get; set; }
        public string ReasonOfDiscontinue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ChronicDiseaseID_FK { get; set; }
        public Nullable<int> ChronicDiseaseSubInfoID_FK { get; set; }
        public Nullable<int> AcutePRNIndicationID_FK { get; set; }
        public Nullable<int> ReferID_FK { get; set; }
        public Nullable<int> InstructedByID_FK { get; set; }
        public string DrName { get; set; }
        public string DrContact { get; set; }
        public string MCRNo { get; set; }
        public string ClinicHosp { get; set; }
        public Nullable<int> InstructedBy2ID_FK { get; set; }
        public string DrNameED { get; set; }
        public string DrContactED { get; set; }
        public string MCRNoED { get; set; }
        public string ClinicHospED { get; set; }
    }
}
