//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_APIOrderTask
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int APIOrderTaskID { get; set; }
        public int APIOrderID_FK { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string TaskName { get; set; }
        public Nullable<int> TaskTypeID { get; set; }
        public Nullable<System.DateTime> TaskStartDateTime { get; set; }
        public Nullable<System.DateTime> TaskEndDateTime { get; set; }
        public Nullable<int> TaskFrequencyID { get; set; }
        public Nullable<int> TaskFrequency { get; set; }
        public Nullable<int> TaskPeriod { get; set; }
        public string TaskPeriodUnit { get; set; }
        public string TaskDisplay { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
        public string Remark { get; set; }
    }
}
