//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_CarePlanSub
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int CarePlanSubID { get; set; }
        public int CarePlanID_FK { get; set; }
        public int SubCarePlanName { get; set; }
        public string Goal { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<int> PersonInCharge { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> GroupCode { get; set; }
        public string CarePlanGroupName { get; set; }
        public Nullable<int> DiseaseID_FK { get; set; }
        public string InterventionStatus { get; set; }
        public string GoalStatus { get; set; }
    }
}
