//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Code
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int CodeId { get; set; }
        public int CodeTypeId_FK { get; set; }
        public string CodeName { get; set; }
        public Nullable<int> Ordering { get; set; }
        public bool IsSystemUsed { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public Nullable<bool> Indication_Acute { get; set; }
        public Nullable<bool> Indication_PRN { get; set; }
        public string Referral_Code { get; set; }
        public Nullable<bool> AllergyReaction_Drug { get; set; }
        public Nullable<bool> AllergyReaction_Others { get; set; }
        public Nullable<int> MedicationGroupID_FK { get; set; }
        public string Status { get; set; }
        public string CurrencyCodeA { get; set; }
        public string CurrencyCodeN { get; set; }
        public string CurrencyInvoiceFooter { get; set; }
        public Nullable<bool> Critical { get; set; }
    }
}
