//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Users
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int UserId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Remarks { get; set; }
        public string Photo { get; set; }
        public string Contact { get; set; }
        public string Designation { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastLogoutDate { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
        public Nullable<System.DateTime> LastLockoutDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
        public string PreviousPasswords { get; set; }
        public string SessionKey { get; set; }
        public Nullable<bool> ResetPassword { get; set; }
        public bool IsDeleted { get; set; }
        public string LocationNow1 { get; set; }
        public string LocationNow2 { get; set; }
        public string LocationNow3 { get; set; }
        public string PostalCodeNow { get; set; }
        public Nullable<System.DateTime> LocationNowModifiedDate { get; set; }
        public Nullable<int> PatientID_FK { get; set; }
        public Nullable<bool> IsExternal { get; set; }
        public Nullable<int> UserOrganizationID_FK { get; set; }
        public Nullable<bool> IsTCAccepted { get; set; }
        public string UserName { get; set; }
    }
}
