//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Thresholds
    {
        public string AuditAction { get; set; }
        public System.DateTime ActionTime { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public decimal minValue { get; set; }
        public decimal maxValue { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<int> createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<decimal> ews_min_1 { get; set; }
        public Nullable<decimal> ews_max_1 { get; set; }
        public Nullable<decimal> ews_min_2 { get; set; }
        public Nullable<decimal> ews_max_2 { get; set; }
        public Nullable<decimal> ews_min_3 { get; set; }
        public Nullable<decimal> ews_max_3 { get; set; }
        public Nullable<decimal> ews_min_4 { get; set; }
        public Nullable<decimal> ews_max_4 { get; set; }
        public Nullable<decimal> ews_min_5 { get; set; }
        public Nullable<decimal> ews_max_5 { get; set; }
        public Nullable<decimal> ews_min_6 { get; set; }
        public Nullable<decimal> ews_max_6 { get; set; }
        public Nullable<decimal> ews_min_7 { get; set; }
        public Nullable<decimal> ews_max_7 { get; set; }
    }
}
