//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillingInvoice()
        {
            this.BillingInvoiceConsumables = new HashSet<BillingInvoiceConsumable>();
            this.BillingInvoiceServices = new HashSet<BillingInvoiceService>();
            this.ReceiptForInvoices = new HashSet<ReceiptForInvoice>();
        }
    
        public int BillingInvoiceID { get; set; }
        public int PatientID_FK { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDueDate { get; set; }
        public string CaseNumber { get; set; }
        public Nullable<int> InitialCareAssessmentID_FK { get; set; }
        public Nullable<int> CareReportID_FK { get; set; }
        public Nullable<bool> Consumable { get; set; }
        public Nullable<bool> SendEmail { get; set; }
        public Nullable<bool> EmailPatient { get; set; }
        public string EmailTo { get; set; }
        public string EmailCC { get; set; }
        public string EmailBCC { get; set; }
        public int CurrencyID_FK { get; set; }
        public decimal TotalCost { get; set; }
        public string Status { get; set; }
        public string GroupNumber { get; set; }
        public short Version { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
    
        public virtual CareReport CareReport { get; set; }
        public virtual Code Code { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingInvoiceConsumable> BillingInvoiceConsumables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingInvoiceService> BillingInvoiceServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptForInvoice> ReceiptForInvoices { get; set; }
    }
}
