//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CareReport()
        {
            this.BillingInvoices = new HashSet<BillingInvoice>();
            this.CareReport1 = new HashSet<CareReport>();
            this.CareReportSocialSupports = new HashSet<CareReportSocialSupport>();
            this.PatientAccessLines = new HashSet<PatientAccessLine>();
            this.PatientAMTs = new HashSet<PatientAMT>();
            this.PatientEBASDEPs = new HashSet<PatientEBASDEP>();
            this.PatientWounds = new HashSet<PatientWound>();
            this.PatientWoundVisits = new HashSet<PatientWoundVisit>();
        }
    
        public int CareReportID { get; set; }
        public int PatientID_FK { get; set; }
        public string CareReportType { get; set; }
        public string Status { get; set; }
        public string SectionStatus { get; set; }
        public string Memo1 { get; set; }
        public string Memo2 { get; set; }
        public string Memo3 { get; set; }
        public string Memo4 { get; set; }
        public string Memo5 { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public Nullable<int> CarePlanID_FK { get; set; }
        public Nullable<int> CareReportID_FK { get; set; }
        public Nullable<System.DateTime> VisitStartDate { get; set; }
        public Nullable<System.DateTime> VisitEndDate { get; set; }
        public Nullable<int> VisitedBy_FK { get; set; }
        public string Subject { get; set; }
        public Nullable<int> VitalSignID_FK { get; set; }
        public string Pain { get; set; }
        public string PainScaleType { get; set; }
        public Nullable<int> PainLevel { get; set; }
        public Nullable<int> PainDescriptionID_FK { get; set; }
        public string SiteOfPain { get; set; }
        public string TypeOfPain { get; set; }
        public string AggravatingFactor { get; set; }
        public string RelievingFactor { get; set; }
        public string Frequency { get; set; }
        public string PainRemarks { get; set; }
        public Nullable<int> NeuroOrMental { get; set; }
        public Nullable<int> Eyes { get; set; }
        public Nullable<int> VerbalResponse { get; set; }
        public Nullable<int> MotorResponse { get; set; }
        public Nullable<int> LeftEyeSize { get; set; }
        public string LeftEyeReaction { get; set; }
        public Nullable<int> RightEyeSize { get; set; }
        public string RightEyeReaction { get; set; }
        public string NeuroRemarks { get; set; }
        public string SectionRequired { get; set; }
        public string PsychoEmotionalSpiritual { get; set; }
        public string PsychoRemarks { get; set; }
        public Nullable<int> AirwayBreathingID_FK { get; set; }
        public Nullable<int> CoughID_FK { get; set; }
        public Nullable<int> O2AidID_FK { get; set; }
        public Nullable<decimal> O2LitresPercent { get; set; }
        public Nullable<decimal> O2Litres { get; set; }
        public string Sunction { get; set; }
        public string CoughAmount { get; set; }
        public string Color { get; set; }
        public string ColorOthers { get; set; }
        public string Consistency { get; set; }
        public string Nebuliser { get; set; }
        public string AirwayBreathingRemarks { get; set; }
        public Nullable<int> CirculationID_FK { get; set; }
        public Nullable<int> LowerEyelidsID_FK { get; set; }
        public Nullable<int> LipsID_FK { get; set; }
        public Nullable<int> CapillaryRefillID_FK { get; set; }
        public Nullable<int> PeripheralPulsesRadialID_FK { get; set; }
        public Nullable<int> PeripheralPulsesPedalID_FK { get; set; }
        public string CirculationRemarks { get; set; }
        public Nullable<int> SleepRestID_FK { get; set; }
        public string DayNightReversal { get; set; }
        public string SleepRestRemarks { get; set; }
        public Nullable<int> TemperatureID_FK { get; set; }
        public string TemperatureInterventions { get; set; }
        public string TemperatureRemarks { get; set; }
        public Nullable<int> BowelCareID_FK { get; set; }
        public Nullable<int> NoOfBowelTimes { get; set; }
        public Nullable<int> BowelType { get; set; }
        public Nullable<int> HowManyDaysBNO { get; set; }
        public string BowelInterventions { get; set; }
        public string Stoma { get; set; }
        public Nullable<System.DateTime> StomaCreatedDate { get; set; }
        public Nullable<decimal> StomaSizeLength { get; set; }
        public Nullable<decimal> StomaSizeBreath { get; set; }
        public string StomaColour { get; set; }
        public string StomaAppearance { get; set; }
        public string StomaProtrusion { get; set; }
        public string StomaPeristomalSkin { get; set; }
        public string StomaEffluent { get; set; }
        public string StomaAmountOfOutput { get; set; }
        public string StomaOstomyProductUsed { get; set; }
        public Nullable<System.DateTime> StomaReviewDate { get; set; }
        public string BowelRemarks { get; set; }
        public Nullable<int> BladderCareID_FK { get; set; }
        public Nullable<int> BladderCareTimes { get; set; }
        public Nullable<int> BladderCareNPU { get; set; }
        public Nullable<int> DiapersID_FK { get; set; }
        public string TypeOfUrine { get; set; }
        public string CharacteristicOfUrine { get; set; }
        public string Dysuria { get; set; }
        public string BladderCareRemarks { get; set; }
        public string PersonalHygieneRemarks { get; set; }
        public Nullable<int> CareReportRehabilitationID_FK { get; set; }
        public string EnvironmentRemarks { get; set; }
        public Nullable<bool> ACP { get; set; }
        public Nullable<System.DateTime> ACP_DoneDate { get; set; }
        public Nullable<System.DateTime> ACP_ReviewDate { get; set; }
        public string OtherTreatment { get; set; }
        public string OtherTreatmentOther { get; set; }
        public string OtherTreatmentRemarks { get; set; }
        public Nullable<int> CareReportSystemInfoID_FK { get; set; }
        public string SectionRequireInput { get; set; }
        public Nullable<int> PatientNutritionID_FK { get; set; }
        public string SkinAndWoundCare { get; set; }
        public string PersonalHygiene { get; set; }
        public string Environment { get; set; }
        public string BreathSounds { get; set; }
        public string BowelSounds { get; set; }
        public string HeartSounds { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingInvoice> BillingInvoices { get; set; }
        public virtual CarePlan CarePlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareReport> CareReport1 { get; set; }
        public virtual CareReport CareReport2 { get; set; }
        public virtual CareReportRehabilitation CareReportRehabilitation { get; set; }
        public virtual CareReportSystemInfo CareReportSystemInfo { get; set; }
        public virtual Code Code { get; set; }
        public virtual Code Code1 { get; set; }
        public virtual Code Code2 { get; set; }
        public virtual Code Code3 { get; set; }
        public virtual Code Code4 { get; set; }
        public virtual Code Code5 { get; set; }
        public virtual Code Code6 { get; set; }
        public virtual Code Code7 { get; set; }
        public virtual Code Code8 { get; set; }
        public virtual Code Code9 { get; set; }
        public virtual Code Code10 { get; set; }
        public virtual Code Code11 { get; set; }
        public virtual Code Code12 { get; set; }
        public virtual Code Code13 { get; set; }
        public virtual Code Code14 { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual PatientNutrition PatientNutrition { get; set; }
        public virtual User User { get; set; }
        public virtual VitalSign VitalSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareReportSocialSupport> CareReportSocialSupports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAccessLine> PatientAccessLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAMT> PatientAMTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientEBASDEP> PatientEBASDEPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientWound> PatientWounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientWoundVisit> PatientWoundVisits { get; set; }
    }
}
