//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarePlanSub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarePlanSub()
        {
            this.CarePlanDetails = new HashSet<CarePlanDetail>();
            this.CarePlanSubGoals = new HashSet<CarePlanSubGoal>();
            this.CarePlanSubProblemLists = new HashSet<CarePlanSubProblemList>();
            this.Activities = new HashSet<Activity>();
            this.CPGoals = new HashSet<CPGoal>();
            this.Interventions = new HashSet<Intervention>();
        }
    
        public int CarePlanSubID { get; set; }
        public int CarePlanID_FK { get; set; }
        public int SubCarePlanName { get; set; }
        public string Goal { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<int> PersonInCharge { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> GroupCode { get; set; }
        public string CarePlanGroupName { get; set; }
        public Nullable<int> DiseaseID_FK { get; set; }
        public string InterventionStatus { get; set; }
        public string GoalStatus { get; set; }
    
        public virtual CarePlan CarePlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarePlanDetail> CarePlanDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarePlanSubGoal> CarePlanSubGoals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarePlanSubProblemList> CarePlanSubProblemLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPGoal> CPGoals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Intervention> Interventions { get; set; }
    }
}
