//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chat()
        {
            this.Chat1 = new HashSet<Chat>();
            this.NotificationChats = new HashSet<NotificationChat>();
        }
    
        public int ChatID { get; set; }
        public string Comment { get; set; }
        public string Attachment { get; set; }
        public string Attachment_Physical { get; set; }
        public Nullable<int> ParentID_FK { get; set; }
        public Nullable<int> PatientID_FK { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> Family { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chat1 { get; set; }
        public virtual Chat Chat2 { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationChat> NotificationChats { get; set; }
    }
}
