//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DischargeSummaryReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DischargeSummaryReport()
        {
            this.DischargeSummaryReportAttachments = new HashSet<DischargeSummaryReportAttachment>();
        }
    
        public int DischargeSummaryReportId { get; set; }
        public int PatientID_FK { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public Nullable<System.DateTime> VisitDateStart { get; set; }
        public Nullable<System.DateTime> VisitDateEnd { get; set; }
        public Nullable<int> VisitedBy_FK { get; set; }
        public string SummaryCaseNote { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DischargeSummaryReportAttachment> DischargeSummaryReportAttachments { get; set; }
    }
}
