//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public int EmailLogId { get; set; }
        public string description { get; set; }
        public string msgBCC { get; set; }
        public string msgCC { get; set; }
        public string msgTo { get; set; }
        public string msgSubj { get; set; }
        public string msgBody { get; set; }
        public string msgFromName { get; set; }
        public string msgFrom { get; set; }
        public Nullable<bool> isHtml { get; set; }
        public string attachmentName { get; set; }
        public Nullable<bool> isSent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string smtpServerAddress { get; set; }
        public string smtpLogin { get; set; }
        public string smtpPassword { get; set; }
        public string smtpPort { get; set; }
    }
}
