//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enquiry()
        {
            this.EnquiryAttachments = new HashSet<EnquiryAttachment>();
            this.Codes = new HashSet<Code>();
            this.Codes1 = new HashSet<Code>();
        }
    
        public int EnquiryID { get; set; }
        public Nullable<int> CareManagerAssignedID_FK { get; set; }
        public Nullable<int> EnquirySourceID_FK { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> RaceID_FK { get; set; }
        public string IdentificationNumber { get; set; }
        public Nullable<int> PreferredLanguageID_FK { get; set; }
        public Nullable<int> GenderID_FK { get; set; }
        public string PatientAddress1 { get; set; }
        public string PatientAddress2 { get; set; }
        public string PatientAddress3 { get; set; }
        public string PostalCode { get; set; }
        public string NameOfCaller { get; set; }
        public string ContactNumberOfCaller { get; set; }
        public string EmailOfCaller { get; set; }
        public Nullable<System.DateTime> PreferredAppointmentDateTime { get; set; }
        public string MedicalHistory { get; set; }
        public Nullable<int> CaregiverAtHomeID_FK { get; set; }
        public Nullable<int> ServicesRequiredID_FK { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string OtherRace { get; set; }
        public string OtherPreferredLanguage { get; set; }
        public Nullable<int> UserOrganizationID_FK { get; set; }
        public string CaseNumber { get; set; }
        public string Note { get; set; }
        public string OrderID { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual Code Code1 { get; set; }
        public virtual Code Code2 { get; set; }
        public virtual Code Code3 { get; set; }
        public virtual Code Code4 { get; set; }
        public virtual Code Code5 { get; set; }
        public virtual Code Code6 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnquiryAttachment> EnquiryAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Code> Codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Code> Codes1 { get; set; }
    }
}
