//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InitialCareAssessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InitialCareAssessment()
        {
            this.InitialCareAssessmentAttachments = new HashSet<InitialCareAssessmentAttachment>();
            this.InitialCareAssessmentSpecialInstructions = new HashSet<InitialCareAssessmentSpecialInstruction>();
            this.PatientAMTs = new HashSet<PatientAMT>();
            this.PatientClinicians = new HashSet<PatientClinician>();
            this.PatientDrugAllergies = new HashSet<PatientDrugAllergy>();
            this.PatientEBASDEPs = new HashSet<PatientEBASDEP>();
            this.PatientFamilyHistories = new HashSet<PatientFamilyHistory>();
            this.PatientOtherAllergies = new HashSet<PatientOtherAllergy>();
            this.PatientSocialSupports = new HashSet<PatientSocialSupport>();
            this.PatientWounds = new HashSet<PatientWound>();
            this.PatientWoundVisits = new HashSet<PatientWoundVisit>();
            this.Tasks = new HashSet<Task>();
            this.Codes = new HashSet<Code>();
        }
    
        public int InitialCareAssessmentID { get; set; }
        public Nullable<int> PatientID_FK { get; set; }
        public string GeneralCondition { get; set; }
        public string Physique { get; set; }
        public string ConsciousLevel { get; set; }
        public string EmotionalState { get; set; }
        public string OtherEmotionalState { get; set; }
        public string Breathing { get; set; }
        public string OtherBreathing { get; set; }
        public Nullable<decimal> O2Litres { get; set; }
        public string O2LitresVia { get; set; }
        public Nullable<System.DateTime> TracheostomyDateInserted { get; set; }
        public string TracheostomySize { get; set; }
        public string TracheostomyType { get; set; }
        public Nullable<bool> IsTracheostomyInnerCannula { get; set; }
        public Nullable<System.DateTime> TracheostomyNextReviewDate { get; set; }
        public string Cough { get; set; }
        public string Vision { get; set; }
        public Nullable<bool> VisionImpairedLeft { get; set; }
        public Nullable<bool> VisionImpairedRight { get; set; }
        public string VisionImpairedRemarks { get; set; }
        public Nullable<bool> VisionImpairedGlaucoma { get; set; }
        public Nullable<bool> VisionImpairedCataract { get; set; }
        public Nullable<bool> VisionImpairedGlaucomaLeft { get; set; }
        public Nullable<bool> VisionImpairedGlaucomaRight { get; set; }
        public string VisionImpairedGlaucomaRemarks { get; set; }
        public Nullable<bool> VisionImpairedCataractLeft { get; set; }
        public Nullable<bool> VisionImpairedCataractRight { get; set; }
        public string VisionImpairedCataractRemarks { get; set; }
        public string Hearing { get; set; }
        public Nullable<bool> HearingImpairedLeft { get; set; }
        public Nullable<bool> HearingImpairedRight { get; set; }
        public string HearingImpairedRemarks { get; set; }
        public Nullable<bool> HearingImpairedWithHearingAidLeft { get; set; }
        public Nullable<bool> HearingImpairedWithHearingAidRight { get; set; }
        public string HearingImpairedWithHearingAidRemarks { get; set; }
        public string BowelHabitsTimes { get; set; }
        public string BowelHabitsDays { get; set; }
        public string BowelType { get; set; }
        public string Stoma { get; set; }
        public Nullable<System.DateTime> StomaCreatedDate { get; set; }
        public Nullable<decimal> StomaSizeLength { get; set; }
        public Nullable<decimal> StomaSizeBreath { get; set; }
        public string StomaColour { get; set; }
        public string StomaAppearance { get; set; }
        public string StomaProtrusion { get; set; }
        public string StomaPeristomalSkin { get; set; }
        public string StomaEffluent { get; set; }
        public string StomaAmountOfOutput { get; set; }
        public string StomaOstomyProductUsed { get; set; }
        public Nullable<System.DateTime> StomaReviewDate { get; set; }
        public string UrinaryFrequencyTimes { get; set; }
        public string UrinaryFrequencyDay { get; set; }
        public string UrinaryTypes { get; set; }
        public string Catheter { get; set; }
        public Nullable<System.DateTime> CatheterDateInserted { get; set; }
        public string CatheterType { get; set; }
        public string CatheterSize { get; set; }
        public Nullable<System.DateTime> CatheterNextReviewDate { get; set; }
        public Nullable<System.DateTime> LMP { get; set; }
        public Nullable<bool> UseOfDrug { get; set; }
        public string UseOfDrugExplain { get; set; }
        public string MedicalHistory { get; set; }
        public Nullable<int> OralCavityAssessmentScore1 { get; set; }
        public Nullable<int> OralCavityAssessmentScore2 { get; set; }
        public Nullable<int> OralCavityAssessmentScore3 { get; set; }
        public Nullable<int> OralCavityAssessmentScore4 { get; set; }
        public Nullable<int> OralCavityAssessmentScore5 { get; set; }
        public Nullable<int> OralCavityAssessmentScore6 { get; set; }
        public string MilkFeedRx { get; set; }
        public Nullable<bool> EmotionalYesNo { get; set; }
        public string EmotionalYes { get; set; }
        public string HowCanIHelp { get; set; }
        public Nullable<bool> LostInterest { get; set; }
        public string LostInterestYes { get; set; }
        public string HowDoYouScope { get; set; }
        public Nullable<bool> DifficultyCoping { get; set; }
        public string DifficultyCopingYes { get; set; }
        public Nullable<bool> Depressed { get; set; }
        public string GetSupport { get; set; }
        public Nullable<bool> ReferCounsellor { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public string Status { get; set; }
        public Nullable<int> PatientProfileID_FK { get; set; }
        public Nullable<int> PatientReferralID_FK { get; set; }
        public string SectionStatus { get; set; }
        public Nullable<int> PatientAdditionalInfoID_FK { get; set; }
        public Nullable<int> VitalSignID_FK { get; set; }
        public Nullable<int> WoundAssessmentScore1 { get; set; }
        public Nullable<int> WoundAssessmentScore2 { get; set; }
        public Nullable<int> WoundAssessmentScore3 { get; set; }
        public Nullable<int> WoundAssessmentScore4 { get; set; }
        public Nullable<int> WoundAssessmentScore5 { get; set; }
        public Nullable<int> WoundAssessmentScore6 { get; set; }
        public Nullable<int> PatientMedicationID_FK { get; set; }
        public Nullable<bool> HomeFacilityVentilation { get; set; }
        public Nullable<bool> HomeFacilityCooking { get; set; }
        public Nullable<bool> HomeFacilityRefrigeration { get; set; }
        public Nullable<bool> HomeFacilityToileting { get; set; }
        public Nullable<bool> HomeFacilityStairs { get; set; }
        public Nullable<bool> HomeFacilityCommunication { get; set; }
        public Nullable<bool> HomeFacilityAffectCaregiver { get; set; }
        public Nullable<bool> HomeFacilityAffectCareManager { get; set; }
        public string HomeFacilityRemarks { get; set; }
        public Nullable<bool> IsRequirePalliativeCare { get; set; }
        public Nullable<int> PainLevel { get; set; }
        public Nullable<int> TirednessLevel { get; set; }
        public Nullable<int> DrowsinessLevel { get; set; }
        public Nullable<int> NauseaLevel { get; set; }
        public Nullable<int> LackOfAppetiteLevel { get; set; }
        public Nullable<int> ShortnessOfBreath { get; set; }
        public Nullable<int> DepressionLevel { get; set; }
        public Nullable<int> AnxietyLevel { get; set; }
        public Nullable<int> BestWellbeing { get; set; }
        public string Faith { get; set; }
        public Nullable<bool> IsReligious { get; set; }
        public string GiveMeaningToLife { get; set; }
        public string MakeSense { get; set; }
        public Nullable<bool> IsBeliefImportant { get; set; }
        public string InfluenceTakeCare { get; set; }
        public string BeliefInfluenced { get; set; }
        public string RoleOfBeliefForInfluence { get; set; }
        public Nullable<bool> IsPartOfCommunity { get; set; }
        public string SupportTo { get; set; }
        public string RoleOfBeliefForCommunity { get; set; }
        public string PersonalConcern { get; set; }
        public string AddressIssue { get; set; }
        public string Concern { get; set; }
        public string TalkToSomeone { get; set; }
        public Nullable<int> OralCavityAssessmentScore7 { get; set; }
        public Nullable<int> OralCavityAssessmentScore8 { get; set; }
        public Nullable<int> PatientNutritionID_FK { get; set; }
        public Nullable<int> PatientRAFID_FK { get; set; }
        public Nullable<int> PatientMBIID_FK { get; set; }
        public Nullable<int> PatientMFSID_FK { get; set; }
        public Nullable<System.DateTime> VisitDateTime { get; set; }
        public Nullable<System.DateTime> VSOnSetDate { get; set; }
        public Nullable<System.DateTime> painOnSetDate { get; set; }
        public string VSQuality { get; set; }
        public string VSPainFrequency { get; set; }
        public string VSIntermittent { get; set; }
        public string VSLocation { get; set; }
        public string VSPrecipitatingFactors { get; set; }
        public string VSRelievingFactors { get; set; }
        public Nullable<int> VSPainFrequencyIntermittentNumber { get; set; }
        public string CAAlertness { get; set; }
        public string CACommunication { get; set; }
        public Nullable<bool> CADementia { get; set; }
        public Nullable<bool> CAdateAndTime { get; set; }
        public Nullable<bool> CAPerson { get; set; }
        public Nullable<bool> CAPlace { get; set; }
        public Nullable<bool> CASituation { get; set; }
        public Nullable<bool> HearingAid { get; set; }
        public Nullable<bool> ChestSymmetry { get; set; }
        public Nullable<bool> AbdomenSymmetry { get; set; }
        public Nullable<bool> AnySkinIssue { get; set; }
        public Nullable<bool> PressureInjuries { get; set; }
        public Nullable<int> ApicalPulse { get; set; }
        public string SkinType { get; set; }
        public string SkinIssue { get; set; }
        public string SkinTurgor { get; set; }
        public string BreathSounds { get; set; }
        public string BowelSounds { get; set; }
        public string Percussion { get; set; }
        public string Palpation { get; set; }
        public string TenderNGuarding { get; set; }
        public string Remark { get; set; }
        public Nullable<int> LeftUpperLimbStrength { get; set; }
        public Nullable<int> RightUpperLimbStrength { get; set; }
        public Nullable<int> LeftLowerLimbStrength { get; set; }
        public Nullable<int> RightLowerLimbStrength { get; set; }
        public string MobilityStatus { get; set; }
        public string AssistiveAids { get; set; }
        public Nullable<bool> Incontinence { get; set; }
        public string IncontinenceType { get; set; }
        public string UrineConsistency { get; set; }
        public string UrineColour { get; set; }
        public string StoolsType { get; set; }
        public Nullable<bool> VisionSpectacles { get; set; }
        public Nullable<bool> OxygenRequired { get; set; }
        public Nullable<bool> Sputum { get; set; }
        public Nullable<bool> SuctioningRequired { get; set; }
        public Nullable<decimal> OxygenLMin { get; set; }
        public string OxygenType { get; set; }
        public string OxygenRemark { get; set; }
        public string Oralhealth { get; set; }
        public string Teeth { get; set; }
        public Nullable<bool> AblePassUrine { get; set; }
        public Nullable<bool> NutritionalImbalance { get; set; }
    
        public virtual PatientAdditionalInfo PatientAdditionalInfo { get; set; }
        public virtual PatientMBI PatientMBI { get; set; }
        public virtual PatientMedication PatientMedication { get; set; }
        public virtual PatientMF PatientMF { get; set; }
        public virtual PatientNutrition PatientNutrition { get; set; }
        public virtual PatientProfile PatientProfile { get; set; }
        public virtual PatientRAF PatientRAF { get; set; }
        public virtual PatientReferral PatientReferral { get; set; }
        public virtual VitalSign VitalSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InitialCareAssessmentAttachment> InitialCareAssessmentAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InitialCareAssessmentSpecialInstruction> InitialCareAssessmentSpecialInstructions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAMT> PatientAMTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientClinician> PatientClinicians { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDrugAllergy> PatientDrugAllergies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientEBASDEP> PatientEBASDEPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientFamilyHistory> PatientFamilyHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientOtherAllergy> PatientOtherAllergies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientSocialSupport> PatientSocialSupports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientWound> PatientWounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientWoundVisit> PatientWoundVisits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Code> Codes { get; set; }
    }
}
