//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginDevice
    {
        public int LoginDeviceId { get; set; }
        public int UserId_FK { get; set; }
        public string DeviceType { get; set; }
        public string DeviceID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
