//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationVitalSignDetail
    {
        public int id { get; set; }
        public int notificationId { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public int VitalSignDetailId { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual VitalSignDetail VitalSignDetail { get; set; }
    }
}
