//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutritionTask
    {
        public int NutritionTaskID { get; set; }
        public int ActionTypeID_FK { get; set; }
        public Nullable<int> PatientID_FK { get; set; }
        public string Food { get; set; }
        public string Liquid { get; set; }
        public string Method { get; set; }
        public string BeforeImage { get; set; }
        public string AfterImage { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TypeReferenceID_FK { get; set; }
        public Nullable<int> AmountReferenceID_FK { get; set; }
        public Nullable<int> ColorReferenceID_FK { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> GivenAmount { get; set; }
        public Nullable<int> TakenAmount { get; set; }
        public string Unit { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual NutritionTaskReference NutritionTaskReference { get; set; }
        public virtual NutritionTaskReference NutritionTaskReference1 { get; set; }
        public virtual NutritionTaskReference NutritionTaskReference2 { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
