//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientClinician
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientClinician()
        {
            this.CareReportSystemInfoes = new HashSet<CareReportSystemInfo>();
            this.CareReportSystemInfoes1 = new HashSet<CareReportSystemInfo>();
            this.PatientMedicalHistories = new HashSet<PatientMedicalHistory>();
            this.PatientReferrals = new HashSet<PatientReferral>();
            this.PatientReferrals1 = new HashSet<PatientReferral>();
            this.PatientReferrals2 = new HashSet<PatientReferral>();
            this.PatientReferrals3 = new HashSet<PatientReferral>();
        }
    
        public int PatientClinicianID { get; set; }
        public Nullable<int> PatientID_FK { get; set; }
        public Nullable<int> InitialCareAssessmentID_FK { get; set; }
        public Nullable<int> UserID_FK { get; set; }
        public Nullable<int> ExternalDoctorID_FK { get; set; }
        public Nullable<int> DiseaseID_FK { get; set; }
        public Nullable<int> DiseaseSubInfoID_FK { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareReportSystemInfo> CareReportSystemInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareReportSystemInfo> CareReportSystemInfoes1 { get; set; }
        public virtual Disease Disease { get; set; }
        public virtual DiseaseSubInfo DiseaseSubInfo { get; set; }
        public virtual ExternalDoctor ExternalDoctor { get; set; }
        public virtual InitialCareAssessment InitialCareAssessment { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMedicalHistory> PatientMedicalHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientReferral> PatientReferrals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientReferral> PatientReferrals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientReferral> PatientReferrals2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientReferral> PatientReferrals3 { get; set; }
    }
}
