//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientOtherAllergy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientOtherAllergy()
        {
            this.PatientOtherAllergy1 = new HashSet<PatientOtherAllergy>();
        }
    
        public int OtherAllergyID { get; set; }
        public Nullable<int> PatientID_FK { get; set; }
        public Nullable<int> InitialCareAssessmentID_FK { get; set; }
        public Nullable<int> ReactionID_FK { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DescriptionID_FK { get; set; }
        public string OtherDescription { get; set; }
        public Nullable<int> ReferID_FK { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual Code Code1 { get; set; }
        public virtual InitialCareAssessment InitialCareAssessment { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientOtherAllergy> PatientOtherAllergy1 { get; set; }
        public virtual PatientOtherAllergy PatientOtherAllergy2 { get; set; }
    }
}
