//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMBI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientMBI()
        {
            this.InitialCareAssessments = new HashSet<InitialCareAssessment>();
        }
    
        public int PatientMBIID { get; set; }
        public string Type { get; set; }
        public Nullable<int> VitalSignDetailID_FK { get; set; }
        public Nullable<int> Score1 { get; set; }
        public Nullable<int> Score2 { get; set; }
        public Nullable<int> Score3 { get; set; }
        public Nullable<int> Score4 { get; set; }
        public Nullable<int> Score5 { get; set; }
        public Nullable<int> Score6 { get; set; }
        public Nullable<int> Score7 { get; set; }
        public Nullable<int> Score8 { get; set; }
        public Nullable<int> Score9 { get; set; }
        public Nullable<int> Score10 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InitialCareAssessment> InitialCareAssessments { get; set; }
        public virtual VitalSignDetail VitalSignDetail { get; set; }
    }
}
