//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientMedicationConsume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientMedicationConsume()
        {
            this.PatientMedicationConsume1 = new HashSet<PatientMedicationConsume>();
            this.PatientMedicationConsumeAttachments = new HashSet<PatientMedicationConsumeAttachment>();
        }
    
        public int PatientMedicationConsumeID { get; set; }
        public int PatientMedicationID_FK { get; set; }
        public Nullable<int> MedicationID_FK { get; set; }
        public Nullable<int> RouteID_FK { get; set; }
        public Nullable<int> DosageID_FK { get; set; }
        public Nullable<int> FrequencyID_FK { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Indication { get; set; }
        public string ReasonOfDiscontinue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ChronicDiseaseID_FK { get; set; }
        public Nullable<int> ChronicDiseaseSubInfoID_FK { get; set; }
        public Nullable<int> AcutePRNIndicationID_FK { get; set; }
        public Nullable<int> ReferID_FK { get; set; }
        public Nullable<int> InstructedByID_FK { get; set; }
        public string DrName { get; set; }
        public string DrContact { get; set; }
        public string MCRNo { get; set; }
        public string ClinicHosp { get; set; }
        public Nullable<int> InstructedBy2ID_FK { get; set; }
        public string DrNameED { get; set; }
        public string DrContactED { get; set; }
        public string MCRNoED { get; set; }
        public string ClinicHospED { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual Code Code1 { get; set; }
        public virtual Code Code2 { get; set; }
        public virtual Code Code3 { get; set; }
        public virtual Code Code4 { get; set; }
        public virtual Code Code5 { get; set; }
        public virtual Code Code6 { get; set; }
        public virtual Disease Disease { get; set; }
        public virtual DiseaseSubInfo DiseaseSubInfo { get; set; }
        public virtual PatientMedication PatientMedication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMedicationConsume> PatientMedicationConsume1 { get; set; }
        public virtual PatientMedicationConsume PatientMedicationConsume2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMedicationConsumeAttachment> PatientMedicationConsumeAttachments { get; set; }
    }
}
