//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientWound
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientWound()
        {
            this.PatientWoundVisits = new HashSet<PatientWoundVisit>();
        }
    
        public int PatientWoundID { get; set; }
        public Nullable<int> PatientID_FK { get; set; }
        public Nullable<int> InitialCareAssessmentID_FK { get; set; }
        public Nullable<System.DateTime> OccurDate { get; set; }
        public Nullable<System.DateTime> SeenDate { get; set; }
        public string Site { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public string LocationOfWound { get; set; }
        public Nullable<int> CareReportID_FK { get; set; }
        public string ActionDescription { get; set; }
        public string Remarks { get; set; }
        public string Category { get; set; }
        public string Stage { get; set; }
        public Nullable<int> WoundStatusID_FK { get; set; }
        public string Comments { get; set; }
    
        public virtual CareReport CareReport { get; set; }
        public virtual Code Code { get; set; }
        public virtual InitialCareAssessment InitialCareAssessment { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientWoundVisit> PatientWoundVisits { get; set; }
    }
}
