//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAMTAnswer
    {
        public int PatientAMTID_FK { get; set; }
        public int AMTQuestionID_FK { get; set; }
        public Nullable<int> Answer { get; set; }
    
        public virtual AMTQuestion AMTQuestion { get; set; }
        public virtual PatientAMT PatientAMT { get; set; }
    }
}
