//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAMT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientAMT()
        {
            this.PatientAMTAnswers = new HashSet<PatientAMTAnswer>();
        }
    
        public int PatientAMTID { get; set; }
        public Nullable<int> PatientID_FK { get; set; }
        public Nullable<int> InitialCareAssessmentID_FK { get; set; }
        public string Alertness { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CareReportID_FK { get; set; }
        public Nullable<int> VitalSignDetailId_FK { get; set; }
    
        public virtual CareReport CareReport { get; set; }
        public virtual InitialCareAssessment InitialCareAssessment { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual VitalSignDetail VitalSignDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAMTAnswer> PatientAMTAnswers { get; set; }
    }
}
