//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientWoundVisit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientWoundVisit()
        {
            this.PatientWoundVisit1 = new HashSet<PatientWoundVisit>();
            this.PatientWoundVisitClinicians = new HashSet<PatientWoundVisitClinician>();
            this.PatientWoundVisitTreatments = new HashSet<PatientWoundVisitTreatment>();
            this.PatientWoundVisitTreatmentLists = new HashSet<PatientWoundVisitTreatmentList>();
            this.Codes = new HashSet<Code>();
            this.Codes1 = new HashSet<Code>();
            this.Codes2 = new HashSet<Code>();
        }
    
        public int PatientWoundVisitID { get; set; }
        public int PatientWoundID_FK { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string WoundType { get; set; }
        public string WoundSubType { get; set; }
        public string WoundTypeOther { get; set; }
        public Nullable<decimal> SizeLength { get; set; }
        public Nullable<decimal> SizeDepth { get; set; }
        public Nullable<decimal> SizeWidth { get; set; }
        public string Edges { get; set; }
        public string Appearance { get; set; }
        public string Smell { get; set; }
        public string UnderMining { get; set; }
        public string Exudate { get; set; }
        public Nullable<int> Suffering { get; set; }
        public string ImageUpload { get; set; }
        public Nullable<decimal> SurfaceArea { get; set; }
        public Nullable<decimal> UnderMiningDepth { get; set; }
        public string ExudateSubInfo { get; set; }
        public Nullable<int> VitalSignID_FK { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public Nullable<int> CareReportID_FK { get; set; }
        public Nullable<int> InitialCareAssessmentID_FK { get; set; }
        public Nullable<int> ReferID_FK { get; set; }
        public Nullable<System.DateTime> NextReviewDate { get; set; }
        public string TreatmentRemarks { get; set; }
        public Nullable<int> AssignedToID_FK { get; set; }
        public string DESIGN_R_Depth { get; set; }
        public int DESIGN_R_Exudate { get; set; }
        public int DESIGN_R_Size { get; set; }
        public int DESIGN_R_Inflammation { get; set; }
        public int DESIGN_R_Granulation { get; set; }
        public int DESIGN_R_Necrotic { get; set; }
        public int DESIGN_R_Pocket { get; set; }
        public int DESIGN_R_Score { get; set; }
        public bool IsDESIGN_R { get; set; }
        public string ExudateSubInfo2 { get; set; }
        public string PeriWound { get; set; }
        public string Debridement { get; set; }
        public string CleansingSolutionUsed { get; set; }
        public string Model_jpg { get; set; }
        public string Model_mtl { get; set; }
        public string Model_obj { get; set; }
        public Nullable<bool> IsDraft { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<bool> WoundInfection { get; set; }
        public Nullable<bool> fever { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public Nullable<bool> abscessPuss { get; set; }
        public Nullable<bool> increasedPain { get; set; }
        public Nullable<bool> erythema { get; set; }
        public Nullable<bool> oedema { get; set; }
        public Nullable<bool> localWarmth { get; set; }
        public Nullable<bool> increasedExcudate { get; set; }
        public Nullable<bool> delayedHealing { get; set; }
        public Nullable<bool> maladour { get; set; }
        public Nullable<bool> pocketing { get; set; }
        public Nullable<bool> suspectedInfection { get; set; }
        public Nullable<decimal> TC_Granulation { get; set; }
        public Nullable<decimal> TC_Slough { get; set; }
        public Nullable<decimal> TC_Necrosis { get; set; }
        public Nullable<decimal> TC_Epithelizing { get; set; }
        public Nullable<decimal> TC_Others { get; set; }
        public string TC_OriginalImage { get; set; }
        public string TC_WoundBedImage { get; set; }
        public string TC_AnnotatedImage { get; set; }
        public Nullable<bool> TC_IsAccept { get; set; }
        public string TC_Reason { get; set; }
        public Nullable<decimal> Perimeter { get; set; }
        public Nullable<decimal> AverageDepth { get; set; }
        public Nullable<decimal> MaximumDepth { get; set; }
        public Nullable<decimal> MinimumDepth { get; set; }
        public Nullable<bool> IsRedness { get; set; }
        public Nullable<bool> IsSwelling { get; set; }
        public Nullable<bool> IsWarmToTouch { get; set; }
        public Nullable<bool> IsSmell { get; set; }
        public Nullable<decimal> Size { get; set; }
        public Nullable<decimal> TC_Auto_Granulation { get; set; }
        public Nullable<decimal> TC_Auto_Slough { get; set; }
        public Nullable<decimal> TC_Auto_Necrosis { get; set; }
        public Nullable<decimal> TC_Auto_Epithelizing { get; set; }
        public Nullable<decimal> TC_Auto_Others { get; set; }
        public Nullable<System.DateTime> NextTreatmentDate { get; set; }
        public string InfectionRemarks { get; set; }
        public string TO_Comments { get; set; }
    
        public virtual CareReport CareReport { get; set; }
        public virtual InitialCareAssessment InitialCareAssessment { get; set; }
        public virtual PatientWound PatientWound { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientWoundVisit> PatientWoundVisit1 { get; set; }
        public virtual PatientWoundVisit PatientWoundVisit2 { get; set; }
        public virtual User User { get; set; }
        public virtual VitalSign VitalSign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientWoundVisitClinician> PatientWoundVisitClinicians { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientWoundVisitTreatment> PatientWoundVisitTreatments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientWoundVisitTreatmentList> PatientWoundVisitTreatmentLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Code> Codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Code> Codes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Code> Codes2 { get; set; }
    }
}
