//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientEBASDEPAnswer
    {
        public int PatientEBASDEPID_FK { get; set; }
        public int EBASDEPQuestionID_FK { get; set; }
        public Nullable<int> Answer { get; set; }
    
        public virtual EBASDEPQuestion EBASDEPQuestion { get; set; }
        public virtual PatientEBASDEP PatientEBASDEP { get; set; }
    }
}
