//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientAdditionalInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientAdditionalInfo()
        {
            this.InitialCareAssessments = new HashSet<InitialCareAssessment>();
            this.Patients = new HashSet<Patient>();
        }
    
        public int PatientAdditionalInfoID { get; set; }
        public Nullable<bool> AICD { get; set; }
        public Nullable<System.DateTime> AICD_InsertDate { get; set; }
        public string AICD_InsertedBy { get; set; }
        public Nullable<System.DateTime> AICD_ReviewDate { get; set; }
        public Nullable<bool> ACP { get; set; }
        public Nullable<System.DateTime> ACP_DoneDate { get; set; }
        public Nullable<System.DateTime> ACP_ReviewDate { get; set; }
        public Nullable<bool> DNR { get; set; }
        public Nullable<bool> Pacemaker { get; set; }
        public Nullable<System.DateTime> Pacemaker_InsertDate { get; set; }
        public string Pacemaker_InsertedBy { get; set; }
        public Nullable<System.DateTime> Pacemaker_ReviewDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public Nullable<System.DateTime> DNR_DateInitiated { get; set; }
        public string DNR_InitiatedBy { get; set; }
        public Nullable<System.DateTime> DNR_DateTerminated { get; set; }
        public string DNR_TerminatedBy { get; set; }
        public Nullable<bool> CVCLine { get; set; }
        public Nullable<System.DateTime> CVCLine_InsertDate { get; set; }
        public string CVCLine_InsertedBy { get; set; }
        public Nullable<System.DateTime> CVCLine_ReviewDate { get; set; }
        public Nullable<bool> PICCLine { get; set; }
        public Nullable<System.DateTime> PICCLine_InsertDate { get; set; }
        public string PICCLine_InsertedBy { get; set; }
        public Nullable<System.DateTime> PICCLine_ReviewDate { get; set; }
        public Nullable<bool> IVLine { get; set; }
        public Nullable<System.DateTime> IVLine_InsertDate { get; set; }
        public string IVLine_InsertedBy { get; set; }
        public Nullable<System.DateTime> IVLine_ReviewDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InitialCareAssessment> InitialCareAssessments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
