//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.BillingInvoices = new HashSet<BillingInvoice>();
            this.BillingProposals = new HashSet<BillingProposal>();
            this.CarePlans = new HashSet<CarePlan>();
            this.CareReports = new HashSet<CareReport>();
            this.Chats = new HashSet<Chat>();
            this.MultiDisciplinaryMeetings = new HashSet<MultiDisciplinaryMeeting>();
            this.NutritionTasks = new HashSet<NutritionTask>();
            this.PatientAMTs = new HashSet<PatientAMT>();
            this.PatientAttachments = new HashSet<PatientAttachment>();
            this.PatientClinicians = new HashSet<PatientClinician>();
            this.PatientDrugAllergies = new HashSet<PatientDrugAllergy>();
            this.PatientEBASDEPs = new HashSet<PatientEBASDEP>();
            this.PatientFamilyHistories = new HashSet<PatientFamilyHistory>();
            this.PatientImmunisations = new HashSet<PatientImmunisation>();
            this.PatientMedicalHistories = new HashSet<PatientMedicalHistory>();
            this.PatientOtherAllergies = new HashSet<PatientOtherAllergy>();
            this.PatientSocialSupports = new HashSet<PatientSocialSupport>();
            this.PatientWounds = new HashSet<PatientWound>();
            this.Receipts = new HashSet<Receipt>();
            this.RecentViews = new HashSet<RecentView>();
            this.Tasks = new HashSet<Task>();
            this.TeleconsultationRecordings = new HashSet<TeleconsultationRecording>();
            this.Users = new HashSet<User>();
            this.VitalSignRelationships = new HashSet<VitalSignRelationship>();
            this.VitalSigns = new HashSet<VitalSign>();
            this.Codes = new HashSet<Code>();
            this.Packages = new HashSet<Package>();
            this.Codes1 = new HashSet<Code>();
        }
    
        public int PatientID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string NRIC { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string PostalCode { get; set; }
        public string Photo { get; set; }
        public Nullable<int> CareManagerAssignedID { get; set; }
        public string CaseID { get; set; }
        public string DrugAllergy { get; set; }
        public string Status { get; set; }
        public Nullable<int> DischargeNoticePeriodInMonths { get; set; }
        public Nullable<System.DateTime> AdmittedDate { get; set; }
        public string ReasonOfAdmission { get; set; }
        public Nullable<bool> AMD { get; set; }
        public Nullable<bool> ACP { get; set; }
        public Nullable<bool> PACEMAKER { get; set; }
        public Nullable<bool> ACID { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string Email { get; set; }
        public string GenogramPicture { get; set; }
        public string ReferringDiagnosis { get; set; }
        public string MailForVitalAlert1 { get; set; }
        public string MailForVitalAlert2 { get; set; }
        public string MailForVitalAlert3 { get; set; }
        public string MailForFamilyNotification1 { get; set; }
        public string MailForFamilyNotification2 { get; set; }
        public string VisitingFrequency { get; set; }
        public Nullable<int> NumberOfChildren { get; set; }
        public string Occupation { get; set; }
        public Nullable<bool> UpfrontPayment { get; set; }
        public Nullable<System.DateTime> CareReviewDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public Nullable<int> PatientTypeID_FK { get; set; }
        public string MailingAddress1 { get; set; }
        public string MailingAddress2 { get; set; }
        public string MailingAddress3 { get; set; }
        public Nullable<int> GenderID_FK { get; set; }
        public Nullable<int> BloodTypeID_FK { get; set; }
        public Nullable<int> ResidentTypeID_FK { get; set; }
        public Nullable<int> MaritalStatusID_FK { get; set; }
        public Nullable<int> ReligionID_FK { get; set; }
        public Nullable<int> PatientProfileID_FK { get; set; }
        public Nullable<int> RaceID_FK { get; set; }
        public Nullable<int> PatientAdditionalInfoID_FK { get; set; }
        public Nullable<int> PatientReferralID_FK { get; set; }
        public string MedicalHistoryRemarks { get; set; }
        public Nullable<int> PatientMedicationID_FK { get; set; }
        public Nullable<int> PatientReferralByID_FK { get; set; }
        public string IdentificationNumber { get; set; }
        public string IdentificationAttachmentFilename { get; set; }
        public string IdentificationAttachmentPhysical { get; set; }
        public string OtherRace { get; set; }
        public string OtherLanguage { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> InvoiceModeID_FK { get; set; }
        public string DisplayName { get; set; }
        public string OrderID { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public string NursingStation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingInvoice> BillingInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingProposal> BillingProposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarePlan> CarePlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CareReport> CareReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chats { get; set; }
        public virtual Code Code { get; set; }
        public virtual Code Code1 { get; set; }
        public virtual Code Code2 { get; set; }
        public virtual Code Code3 { get; set; }
        public virtual Code Code4 { get; set; }
        public virtual Code Code5 { get; set; }
        public virtual Code Code6 { get; set; }
        public virtual Code Code7 { get; set; }
        public virtual Code Code8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MultiDisciplinaryMeeting> MultiDisciplinaryMeetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NutritionTask> NutritionTasks { get; set; }
        public virtual PatientAdditionalInfo PatientAdditionalInfo { get; set; }
        public virtual PatientMedication PatientMedication { get; set; }
        public virtual PatientProfile PatientProfile { get; set; }
        public virtual PatientReferral PatientReferral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAMT> PatientAMTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAttachment> PatientAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientClinician> PatientClinicians { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientDrugAllergy> PatientDrugAllergies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientEBASDEP> PatientEBASDEPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientFamilyHistory> PatientFamilyHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientImmunisation> PatientImmunisations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMedicalHistory> PatientMedicalHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientOtherAllergy> PatientOtherAllergies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientSocialSupport> PatientSocialSupports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientWound> PatientWounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecentView> RecentViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeleconsultationRecording> TeleconsultationRecordings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VitalSignRelationship> VitalSignRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VitalSign> VitalSigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Code> Codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Code> Codes1 { get; set; }
    }
}
