//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemListGoal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProblemListGoal()
        {
            this.CarePlanSubProblemListGoals = new HashSet<CarePlanSubProblemListGoal>();
        }
    
        public int ProblemListGoalID { get; set; }
        public int ProblemListID_FK { get; set; }
        public string Goal { get; set; }
        public Nullable<int> Action { get; set; }
        public Nullable<int> ScoreTypeID { get; set; }
        public Nullable<int> OperatorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarePlanSubProblemListGoal> CarePlanSubProblemListGoals { get; set; }
        public virtual Code Code { get; set; }
        public virtual Code Code1 { get; set; }
        public virtual ProblemList ProblemList { get; set; }
    }
}
