//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int ResourceId { get; set; }
        public int CodeId { get; set; }
        public int LanguageId { get; set; }
        public string CodeValue { get; set; }
        public string Details { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual Language Language { get; set; }
    }
}
