//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.NotificationTasks = new HashSet<NotificationTask>();
            this.TaskFileAttachments = new HashSet<TaskFileAttachment>();
            this.TaskSpecificDates = new HashSet<TaskSpecificDate>();
            this.TaskUsers = new HashSet<TaskUser>();
            this.TaskUserLogs = new HashSet<TaskUserLog>();
            this.Codes = new HashSet<Code>();
        }
    
        public int TaskID { get; set; }
        public int ActionTypeID_FK { get; set; }
        public Nullable<int> PatientID_FK { get; set; }
        public Nullable<int> InitialCareAssessmentID_FK { get; set; }
        public string Description { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Location { get; set; }
        public string OtherLocation { get; set; }
        public Nullable<int> FrequencyID_FK { get; set; }
        public Nullable<int> DosageID_FK { get; set; }
        public Nullable<decimal> MilkFeedVolumeMLS { get; set; }
        public string Supplement { get; set; }
        public Nullable<decimal> H2OFlushingMLS { get; set; }
        public string ReferenceType { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<bool> Pending { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> MedicationID_FK { get; set; }
        public Nullable<int> Recurrence_Frequency { get; set; }
        public Nullable<int> Recurrence_Days { get; set; }
        public Nullable<int> Recurrence_Interval { get; set; }
        public Nullable<int> Recurrence_IntervalFlag { get; set; }
        public string MedicationInstructions { get; set; }
        public Nullable<int> recurrenceDailyHourly { get; set; }
    
        public virtual Code Code { get; set; }
        public virtual Code Code1 { get; set; }
        public virtual Code Code2 { get; set; }
        public virtual Code Code3 { get; set; }
        public virtual InitialCareAssessment InitialCareAssessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationTask> NotificationTasks { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskFileAttachment> TaskFileAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskSpecificDate> TaskSpecificDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskUser> TaskUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskUserLog> TaskUserLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Code> Codes { get; set; }
    }
}
