//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TD_WoundAssessmentFactor
    {
        public int TD_WoundAssessmentID_FK { get; set; }
        public int CodeID_FK { get; set; }
    
        public virtual Code Code { get; set; }
    }
}
