//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeleconsultationReport
    {
        public int TeleReportID { get; set; }
        public int MediaType { get; set; }
        public int TaskID_FK { get; set; }
        public int PatientID_FK { get; set; }
        public string Memo { get; set; }
        public string Status { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy_FK { get; set; }
        public Nullable<int> ModifiedBy_FK { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
