//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VitalSignRelationship
    {
        public int id { get; set; }
        public int vitalSignTypeId { get; set; }
        public int patientId { get; set; }
        public int thresholdId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Threshold Threshold { get; set; }
        public virtual VitalSignType VitalSignType { get; set; }
    }
}
