//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VitalSignDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VitalSignDetail()
        {
            this.NotificationVitalSignDetails = new HashSet<NotificationVitalSignDetail>();
            this.PatientAMTs = new HashSet<PatientAMT>();
            this.PatientBradenScales = new HashSet<PatientBradenScale>();
            this.PatientEBASDEPs = new HashSet<PatientEBASDEP>();
            this.PatientGCS = new HashSet<PatientGC>();
            this.PatientMBIs = new HashSet<PatientMBI>();
            this.PatientMFS = new HashSet<PatientMF>();
            this.PatientMMSEs = new HashSet<PatientMMSE>();
            this.PatientRAFs = new HashSet<PatientRAF>();
        }
    
        public int id { get; set; }
        public int vitalSignTypeId { get; set; }
        public int vitalSignId { get; set; }
        public decimal detailValue { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationVitalSignDetail> NotificationVitalSignDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientAMT> PatientAMTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientBradenScale> PatientBradenScales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientEBASDEP> PatientEBASDEPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientGC> PatientGCS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMBI> PatientMBIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMF> PatientMFS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientMMSE> PatientMMSEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientRAF> PatientRAFs { get; set; }
        public virtual VitalSign VitalSign { get; set; }
        public virtual VitalSignType VitalSignType { get; set; }
    }
}
