//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VitalSignType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VitalSignType()
        {
            this.DiseaseVitalSignTypes = new HashSet<DiseaseVitalSignType>();
            this.MedicationVitalSignTypes = new HashSet<MedicationVitalSignType>();
            this.VitalSignDetails = new HashSet<VitalSignDetail>();
            this.VitalSignRelationships = new HashSet<VitalSignRelationship>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<int> createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiseaseVitalSignType> DiseaseVitalSignTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicationVitalSignType> MedicationVitalSignTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VitalSignDetail> VitalSignDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VitalSignRelationship> VitalSignRelationships { get; set; }
        public virtual VitalSignTypeThreshold VitalSignTypeThreshold { get; set; }
    }
}
