//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CarePlanSystemDisease
    {
        public int CarePlanID { get; set; }
        public int SystemID_FK { get; set; }
        public int DiseaseID_FK { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsClosed { get; set; }
    }
}
