//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CarePlanSetup
    {
        public int PatientID { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public int InitialCareAssessmentID { get; set; }
        public int DiseaseID { get; set; }
        public string DiseaseName { get; set; }
        public int SystemID_FK { get; set; }
        public string System { get; set; }
        public string Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DiseaseSubInfoID { get; set; }
        public string DiseaseSubInfo { get; set; }
    }
}
