//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FalangaScores
    {
        public int patientwoundvisitID { get; set; }
        public string HealingEdges { get; set; }
        public int HealingEdges_Score { get; set; }
        public string BlackEschar { get; set; }
        public int BlackEschar_Score { get; set; }
        public string GreatestWoundDepth { get; set; }
        public int GreatestWoundDepth_Score { get; set; }
        public string ExudateAmount { get; set; }
        public int ExudateAmount_Score { get; set; }
        public Nullable<bool> Edema { get; set; }
        public int Edema_Score { get; set; }
        public string PeriwoundDermatitis { get; set; }
        public int PeriwoundDermatitis_Score { get; set; }
        public string PeriwoundCallousFibrosis { get; set; }
        public int PeriwoundCallousFibrosis_Score { get; set; }
        public string PinkWoundBed { get; set; }
        public int PinkWoundBed_Score { get; set; }
        public Nullable<int> TotalScore { get; set; }
    }
}
