//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetsuyu.Entities.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PushScores
    {
        public int PatientWoundVisitID { get; set; }
        public int LengthXWidthScore { get; set; }
        public int ExudateAmountScore { get; set; }
        public int TissueTypeScore { get; set; }
        public Nullable<int> TotalScore { get; set; }
    }
}
